#!/usr/bin/env bash

source "$INSTALLER_UTILS/print.sh"
source "$INSTALLER_UTILS/installer-data.sh"

_inst_step_hasrun "$(basename $0)"

_inst_data_load "hosting"

debconf-set-selections <<< "postfix postfix/mailname string $MAILSRV_FQDN"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

apt-get install -y mariadb-server \
    postfix postfix-mysql \
    dovecot-mysql dovecot-imapd dovecot-lmtpd dovecot-managesieved \
    apache2 \
    php libapache2-mod-php php-imagick php-curl php-fpm php-gd php-imap php-intl \
    php-ldap php-mbstring php-mysql php-xml php-zip \
    adminer rspamd swaks mutt \
    ca-certificates fail2ban

_inst_step_success "$(basename $0)"
